### DISCUSSION TITLE
"unable to initialize libusb: -99" when installed to an alpine linux docker image

### DISCUSSION THREAD

**Discussion by MechanicalMink** [libusb/libusb#1506] [Q&A]
To recreate, do the following:

Dockerfile:
```
FROM python:3.11-alpine
WORKDIR /app
RUN apk update
RUN pip install --upgrade pip
RUN apk add usbutils
RUN apk add libusb-dev
RUN apk add pciutils
```

compose.yml
```
version: "3.8"
services:
  web:
    container_name: alpine-linux-test
    devices: #comment out if you don't have a USB device to test with
      - /dev/usb/lp0:/dev/usb/lp0 #comment out if you don't have a USB device to test with
    command: sleep infinity
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8013:8013"
    restart: unless-stopped
```

build with:
`docker compose up -d --force-recreate --build
`

test by opening a shell to the container and trying to run "lsusb"
```
docker exec -it alpine-linux-test sh
lsusb
```
The error will be triggered.

Confirm that a USB controller is detected with "lspci", and you should see that there is-- (If not, try running on a Pi 4. That's what I'm doing. Not sure if the USB controller is a virtual device or not, as I'm just getting into docker)
